# Generated by Django 5.1.1 on 2025-06-20 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField()),
                ('file_link', models.TextField()),
                ('service_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('taxes_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('IBAN', 'IBAN'), ('MB WAY', 'MB WAY'), ('Referência Multibanco', 'Referência Multibanco')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField()),
                ('file_link', models.TextField()),
                ('service_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('taxes_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('IBAN', 'IBAN'), ('MB WAY', 'MB WAY'), ('Referência Multibanco', 'Referência Multibanco')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
