# Generated by Django 5.1.1 on 2025-06-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField()),
                ('file_link', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Referência Multibanco', 'Referência Multibanco'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('MB WAY', 'MB WAY'), ('Dinheiro', 'Dinheiro')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Paga', 'Paga'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file_link', models.TextField()),
                ('payment_method', models.CharField(choices=[('Referência Multibanco', 'Referência Multibanco'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('MB WAY', 'MB WAY'), ('Dinheiro', 'Dinheiro')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Paga', 'Paga'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
            ],
        ),
    ]
