# Generated by Django 5.1.1 on 2025-06-20 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_customer_invoice_and_more'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
