# Generated by Django 5.1.1 on 2025-06-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_customer_invoice_and_more'),
        ('financial', '0002_customerinvoice_booking_partnerinvoice_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='partnerinvoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_invoice', to='booking.booking'),
        ),
    ]
