# Generated by Django 5.1.1 on 2025-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_customerinvoice_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='payment_method',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('IBAN', 'IBAN'), ('MB WAY', 'MB WAY'), ('Referência Multibanco', 'Referência Multibanco')], default='Referência Multibanco', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerinvoice',
            name='payment_method',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('IBAN', 'IBAN'), ('MB WAY', 'MB WAY'), ('Referência Multibanco', 'Referência Multibanco')], default='Referência Multibanco', max_length=50),
        ),
    ]
