# Generated by Django 5.1.1 on 2025-06-20 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_channel_alter_booking_status'),
        ('financial', '0005_customerinvoice_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerinvoice',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
