# Generated by Django 5.1.1 on 2025-06-20 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0003_alter_partner_status'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=100)),
                ('client_nif', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('client_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('experience_date', models.DateTimeField()),
                ('number_adults', models.PositiveIntegerField(default=1)),
                ('number_children', models.PositiveIntegerField(default=0)),
                ('price_adults', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_children', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Wordpress', 'Wordpress'), ('Whatsapp', 'Whatsapp')], default='Wordpress', max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado (Cliente)', 'Cancelado (Cliente)'), ('Cancelado (Parceiro)', 'Cancelado (Parceiro)')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bkg_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_booking', to='financial.customerinvoice')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_booking', to='experience.experience')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_booking', to='experience.partner')),
                ('partner_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_booking', to='financial.partnerinvoice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bkg_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
