# Generated by Django 5.1.1 on 2025-06-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file_link', models.TextField()),
                ('payment_method', models.CharField(choices=[('Referência Multibanco', 'Referência Multibanco'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('MB WAY', 'MB WAY'), ('Dinheiro', 'Dinheiro')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Paga', 'Paga'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('emission_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('file_link', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Referência Multibanco', 'Referência Multibanco'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('MB WAY', 'MB WAY'), ('Dinheiro', 'Dinheiro')], default='Referência Multibanco', max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Paga', 'Paga'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=100)),
                ('client_nif', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('client_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('experience_date', models.DateTimeField()),
                ('number_adults', models.PositiveIntegerField(default=1)),
                ('number_children', models.PositiveIntegerField(default=0)),
                ('price_adults', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_children', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channel', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Wordpress', 'Wordpress'), ('Whatsapp', 'Whatsapp')], default='Wordpress', max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada (Cliente)', 'Cancelada (Cliente)'), ('Cancelada (Parceiro)', 'Cancelada (Parceiro)')], default='Pendente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_experience', to='experience.experience')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_partner', to='experience.partner')),
            ],
        ),
    ]
