# Generated by Django 5.1.1 on 2025-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_invoice',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='partner_invoice',
        ),
    ]
