# Generated by Django 5.1.1 on 2025-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_children',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
