# Generated by Django 5.1.1 on 2025-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='channel',
            field=models.CharField(choices=[('Email', 'Email'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Wordpress', 'Wordpress'), ('Whatsapp', 'Whatsapp')], default='Wordpress', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado (Cliente)', 'Cancelado (Cliente)'), ('Cancelado (Parceiro)', 'Cancelado (Parceiro)')], default='Pendente', max_length=30),
        ),
    ]
