# Generated by Django 5.1.1 on 2025-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_client_email_alter_booking_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
