# Generated by Django 5.1.1 on 2025-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_nif',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
