# Generated by Django 5.1.1 on 2025-06-17 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('wordpress_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(message='URL inválida! Certifique-se de que a URL está correta.')])),
                ('category', models.CharField(choices=[('Almoços de Degustação', 'Almoços de Degustação'), ('Cruzeiros de 2 dias', 'Cruzeiros de 2 dias'), ('Cruzeiros no Douro', 'Cruzeiros no Douro'), ('Cruzeiros Privados e Premium', 'Cruzeiros Privados e Premium'), ('Cruzeiros Temáticos', 'Cruzeiros Temáticos'), ('Despedidas de Solteiro', 'Despedidas de Solteiro'), ('Estadia & Escapadinhas', 'Estadia & Escapadinhas'), ('Eventos com harmonização vínica', 'Eventos com harmonização vínica'), ('Eventos Corporativos', 'Eventos Corporativos'), ('Experiências para 2', 'Experiências para 2'), ('Experiências Vínicas', 'Experiências Vínicas'), ('Fins-de-semana Vínicos', 'Fins-de-semana Vínicos'), ('Gastronomia & Tradição', 'Gastronomia & Tradição'), ('Grupos & Empresas', 'Grupos & Empresas'), ('Grupos Privados', 'Grupos Privados'), ('Jantares e Almoços Vínicos', 'Jantares e Almoços Vínicos'), ('Jantares Temáticos', 'Jantares Temáticos'), ('Packs Românticos', 'Packs Românticos'), ('Piqueniques nas Vinhas', 'Piqueniques nas Vinhas'), ('Presentes de Última Hora', 'Presentes de Última Hora'), ('Presentes & Vouchers', 'Presentes & Vouchers'), ('Provas de Vinho', 'Provas de Vinho'), ('Roteiros Personalizados', 'Roteiros Personalizados'), ('Saídas da Régua', 'Saídas da Régua'), ('Saídas do Porto', 'Saídas do Porto'), ('Sem categoria', 'Sem categoria'), ('Vindimas & Eventos Sazonais', 'Vindimas & Eventos Sazonais'), ('Visitas a Quintas e Cavas', 'Visitas a Quintas e Cavas')], default='Sem categoria', max_length=50)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('contact_email', models.EmailField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Email inválido! Certifique-se de que o email informado está correto.')])),
                ('contact_phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(message='URL inválida! Certifique-se de que a URL está correta.')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Bloqueado', 'Bloqueado'), ('Excluído', 'Excluído'), ('Inativo', 'Inativo')], default='Ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
