# Generated by Django 5.1.1 on 2025-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Bloqueado', 'Bloqueado'), ('Excluído', 'Excluído'), ('Inativo', 'Inativo')], default='Ativo', max_length=30),
        ),
    ]
