# Generated by Django 5.1.1 on 2025-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='r8NzxhoA89jQijV9xkcEGwnkDBUisvTf', editable=False, max_length=32, unique=True),
        ),
    ]
