# Generated by Django 5.1.1 on 2025-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yF33mFC10CiIn97sX3kxqVjDdWmZ5dGR', editable=False, max_length=32, unique=True),
        ),
    ]
