# Generated by Django 5.1.1 on 2025-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gVI3xQurdFK5hvTfYh1q3hnsaqxIvmNM', editable=False, max_length=32, unique=True),
        ),
    ]
