# Generated by Django 5.1.1 on 2025-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='022Z8z5yihSmoH8OiZKM0fpuvZ6a6fxI', editable=False, max_length=32, unique=True),
        ),
    ]
